{{- if .Values.scraper.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scraper.serviceAccountName" . }}
  labels:
    {{- include "scraper.labels" . | nindent 4 }}
  {{- with .Values.scraper.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.scraper.serviceAccount.automount }}
{{- end }}
