// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: protos/event/event.proto

package event

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EventHandlerClient is the client API for EventHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventHandlerClient interface {
	// Sends a greeting
	SendEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error)
}

type eventHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewEventHandlerClient(cc grpc.ClientConnInterface) EventHandlerClient {
	return &eventHandlerClient{cc}
}

func (c *eventHandlerClient) SendEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := c.cc.Invoke(ctx, "/protos.EventHandler/SendEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventHandlerServer is the server API for EventHandler service.
// All implementations must embed UnimplementedEventHandlerServer
// for forward compatibility
type EventHandlerServer interface {
	// Sends a greeting
	SendEvent(context.Context, *Event) (*Event, error)
	mustEmbedUnimplementedEventHandlerServer()
}

// UnimplementedEventHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedEventHandlerServer struct {
}

func (UnimplementedEventHandlerServer) SendEvent(context.Context, *Event) (*Event, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedEventHandlerServer) mustEmbedUnimplementedEventHandlerServer() {}

// UnsafeEventHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventHandlerServer will
// result in compilation errors.
type UnsafeEventHandlerServer interface {
	mustEmbedUnimplementedEventHandlerServer()
}

func RegisterEventHandlerServer(s grpc.ServiceRegistrar, srv EventHandlerServer) {
	s.RegisterService(&EventHandler_ServiceDesc, srv)
}

func _EventHandler_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventHandlerServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.EventHandler/SendEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventHandlerServer).SendEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

// EventHandler_ServiceDesc is the grpc.ServiceDesc for EventHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.EventHandler",
	HandlerType: (*EventHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEvent",
			Handler:    _EventHandler_SendEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/event/event.proto",
}
