version: 1
environment: dev
serve:
  port: 8088
db:
  selectedDb:
    read: redis
    write: redis
  cache:
    name: "redis"
    addr: "localhost:6379"
  persistent:
    name: "mongodb"
    uri: "mongodb://localhost:27017"
