version: 1
environment: dev
serve:
  port: 8088
web:
  allowedOrigins:
    - "*"
messaging:
  nats:
    url: nats://127.0.0.1:4222
    js: true
    streams:
      - "events"
    consumers:
      - name: "consumer-event"
        stream: events
cacheDirect:
  enabled: false
scraper:
  server:
    host: "localhost"
    port: 50077
db:
  selectedDb:
    read: mongodb
    write: mongodb
  cache:
    name: "redis"
    addr: "localhost:6379"
  persistent:
    name: "mongodb"
    uri: "mongodb://localhost:27017"
    rs: "rs"
