version: 1
environment: dev
serve:
  port: 8088
web:
  allowedOrigins:
    - "*"
cache:
  enabled: true
scraper:
  server:
    host: "localhost"
    port: 50077
db:
  selectedDb:
    read: mongodb
    write: mongodb
  cache:
    name: "redis"
    addr: "localhost:6379"
  persistent:
    name: "mongodb"
    uri: "mongodb://localhost:27017"
