openapi: 3.0.0
info:
  version: 1.0.0
  title: API server

components:
  schemas:
    # base types
    ApiResponse:
      type: object
      properties:
        msg:
          type: object
        code:
          type: integer
    Selection:
      type: object
      required:
        - query
        - selection
      properties:
        query:
          type: string
        selection:
          type: string
    SearchResponse :
      type: array
      items:
       type: string
    Error:
      type: object
      required:
        - msg
      properties:
        msg:
          type: string

