openapi: 3.0.0
info:
  version: 1.0.0
  title: API server

components:
  schemas:
    # base types
    Items:
      type: object
      properties:
        title:
          type: string
        url:
          type: string
    ResultsResponse:
      type: object
      properties:
        items:
            $ref: '#/components/schemas/Items'
    ApiResponse:
      type: object
      properties:
        data:
          type: object
        msg:
          type: string
        code:
          type: integer
    RecordRequest:
      type: object
      required:
        - data
      properties:
        data:
          type: string
    SelectionRequest:
      type: object
      required:
        - query
        - selectedKey
      properties:
        query:
          type: string
        selectedKey:
          type: string
    SearchResponse :
      type: array
      items:
       type: string
    SEError:
      type: object
      properties:
        kind:
          type: string
          x-go-type-skip-optional-pointer: true
          enum:
            - db
            - messaging
        error:
          type: string
          x-go-type-skip-optional-pointer: true
        dbName:
          type: string
          x-go-type-skip-optional-pointer: true
        key:
          type: string
          x-go-type-skip-optional-pointer: true
        value:
          type: string
          x-go-type-skip-optional-pointer: true
    Error:
      type: object
      required:
        - msg
      properties:
        msg:
          type: string

