// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package types

// ApiResponse defines model for ApiResponse.
type ApiResponse struct {
	Code *int                    `json:"code,omitempty"`
	Msg  *map[string]interface{} `json:"msg,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Msg string `json:"msg"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse = []string

// Selection defines model for Selection.
type Selection struct {
	Query     string `json:"query"`
	Selection string `json:"selection"`
}
