// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package types

// Error defines model for Error.
type Error struct {
	Msg string `json:"msg"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse = []string
