version: 1
environment: dev
serve:
  port: 8087
web:
  allowedOrigins:
    - "*"
db:
  selectedDb:
    read: redis
  cache:
    name: "redis"
    addr: "localhost:6379"
  persistent:
    name: "mongodb"
    uri: "mongodb://localhost:27017"



#version: 1
#environment: prod
#serve:
#  port: 8087
#web:
#  allowedOrigins:
#    - "*"
#db:
#  selectedDb:
#    read: redis
#  cache:
#    name: "redis"
#    addr: "searchengine-redis:6379"
#    pass: "password"
#  persistent:
#    name: "mongodb"
#    uri: "mongodb://mongodb:27017"