version: 1
environment: dev
serve:
  port: 8087
web:
  allowedOrigins:
    - "*"
messaging:
  nats:
    url: nats://127.0.0.1:4222
    js: true
    streams:
      - "events"
    consumers:
      - name: "consumer-event"
        stream: events
db:
  selectedDb:
    read: redis
    write: redis
  cache:
    name: "redis"
    addr: "localhost:6379"
  persistent:
    name: "redis"
    uri: "mongodb://localhost:27017"