version: 1
environment: prod
serve:
  port: 8087
web:
  allowedOrigins:
    - "*"
db:
  selectedDb:
    read: redis
  cache:
    name: "redis"
    addr: "searchengine-redis:6379"
  persistent:
    name: "mongodb"
    uri: "mongodb://mongodb:27017"