apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "writeApi.fullname" . }}
  labels:
    {{- include "writeApi.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.writeApi.yamlConfig }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
