apiVersion: v1
kind: Service
metadata:
  name: {{ include "writeApi.fullname" . }}
  labels:
    {{- include "writeApi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.writeApi.service.type }}
  ports:
    - port: {{ .Values.writeApi.service.port }}
      targetPort: {{ .Values.writeApi.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "writeApi.selectorLabels" . | nindent 4 }}
