{{- if .Values.writeApi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "writeApi.serviceAccountName" . }}
  labels:
    {{- include "writeApi.labels" . | nindent 4 }}
  {{- with .Values.writeApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.writeApi.serviceAccount.automount }}
{{- end }}
