apiVersion: v1
kind: Service
metadata:
  name: {{ include "writeApi.fullname" . }}
  labels:
    {{- include "writeApi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.writeApi.service.type }}
  ports:
    {{- range .Values.writeApi.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end}}
  selector:
    {{- include "writeApi.selectorLabels" . | nindent 4 }}
