apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "projection.fullname" . }}
  labels:
    {{- include "projection.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.projection.yamlConfig }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
