{{- if .Values.projection.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "projection.serviceAccountName" . }}
  labels:
    {{- include "projection.labels" . | nindent 4 }}
  {{- with .Values.projection.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.projection.serviceAccount.automount }}
{{- end }}
