apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scraper.fullname" . }}
  labels:
    {{- include "scraper.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.scraper.yamlConfig }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
