apiVersion: v1
kind: Service
metadata:
  name: {{ include "scraper.fullname" . }}
  labels:
    {{- include "scraper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.scraper.service.type }}
  ports:
    {{- range .Values.scraper.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end}}
  selector:
    {{- include "scraper.selectorLabels" . | nindent 4 }}
