apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "readApi.fullname" . }}
  labels:
    {{- include "readApi.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.readApi.yamlConfig }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
