{{- if .Values.readApi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "readApi.serviceAccountName" . }}
  labels:
    {{- include "readApi.labels" . | nindent 4 }}
  {{- with .Values.readApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.readApi.serviceAccount.automount }}
{{- end }}
