openapi: "3.0.0"
info:
  version: 1.0.0
  title: Minimal ping API server
servers:
  - url: http://localhost:8088/{basePath}
    variables:
      basePath:
        default: v1
  - url: https://cemayan.com/{basePath}
    variables:
      basePath:
        default: v1
paths:
  /record:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RecordRequest"
      responses:
        '201':
          description: record response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /selection:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Selection"
      responses:
        '201':
          description: selection response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
components:
  schemas:
    ApiResponse:
      $ref: "../../types/spec.yaml#/components/schemas/ApiResponse"
    Selection:
      $ref: "../../types/spec.yaml#/components/schemas/Selection"
    RecordRequest:
      $ref: "../../types/spec.yaml#/components/schemas/RecordRequest"
