openapi: "3.0.0"
info:
  version: 1.0.0
  title: Minimal ping API server
servers:
  - url: http://localhost:8088/{basePath}
    variables:
      basePath:
        default: v1
  - url: https://cemayan.com/{basePath}
    variables:
      basePath:
        default: v1
paths:
  /record:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RecordRequest"
      responses:
        '201':
          description: record response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /selection:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SelectionRequest"
      responses:
        '201':
          description: selection response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
  /health:
    get:
      summary: Health check endpoint
      security: [ ]
      responses:
        "200":
          description: healthy
components:
  schemas:
    ApiResponse:
      $ref: "../../types/spec.yaml#/components/schemas/ApiResponse"
    SelectionRequest:
      $ref: "../../types/spec.yaml#/components/schemas/SelectionRequest"
    RecordRequest:
      $ref: "../../types/spec.yaml#/components/schemas/RecordRequest"
