name: buildpush

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Readapi Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/api/read/Dockerfile
          push: true
          tags: cemayan/readapi:v1
      - name: Writeapi Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/api/write/Dockerfile
          push: true
          tags: cemayan/writeapi:v1
      - name: Web app Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/app/Dockerfile
          push: true
          tags: cemayan/app:v1
      - name: Scraper Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: build/scraper/Dockerfile
          push: true
          tags: cemayan/scraper:v1